skills_list = [
    "accountability",
    "active listening",
    "adaptability",
    "analytical thinking",
    "attention to detail",
    "brainstorming",
    "building consensus",
    "collaboration",
    "conflict management",
    "conflict mediation",
    "conflict resolution",
    "creativity",
    "critical thinking",
    "cross-cultural communication",
    "customer relationship management",
    "decision-making",
    "delegation",
    "diversity awareness",
    "emotional intelligence",
    "emotional regulation",
    "empathy",
    "experimentation",
    "explaining concepts clearly",
    "feedback delivery",
    "flexibility",
    "goal setting",
    "handling change",
    "idea generation",
    "inclusion advocacy",
    "integrity",
    "interpersonal skills",
    "leadership",
    "logical reasoning",
    "mentoring",
    "motivating others",
    "multitasking",
    "negotiation",
    "networking",
    "non-verbal communication",
    "open-mindedness",
    "patience",
    "persuasion",
    "prioritization",
    "problem management",
    "problem resolution",
    "problem-solving",
    "professionalism",
    "public speaking",
    "punctuality",
    "relationship building",
    "reliability",
    "research",
    "resilience",
    "responsibility",
    "scheduling",
    "self-awareness",
    "self-regulation",
    "social skills",
    "storytelling",
    "stress management",
    "stress tolerance",
    "supporting others",
    "teamwork",
    "time management",
    "vision and goal setting",
    "verbal communication",
    "work ethic",
    "written communication",
    "ajax",
    "amazon dynamodb",
    "amazon s3",
    "amazon web services (aws)",
    "android development",
    "angular",
    "ansible",
    "apache camel",
    "apache flink",
    "apache hadoop",
    "apache kafka",
    "apache spark",
    "api development",
    "asp.net",
    "assembly language",
    "aws lambda",
    "aws rds",
    "aws sagemaker",
    "azure",
    "azure devops",
    "backbone.js",
    "big data analytics",
    "blockchain development",
    "bootstrap",
    "c",
    "c++",
    "ci/cd pipelines",
    "chakra ui",
    "chart.js",
    "circleci",
    "cloud computing",
    "cocoa",
    "codeigniter",
    "containerization",
    "couchbase",
    "css",
    "cucumber",
    "cypress",
    "d3.js",
    "data structures",
    "datadog",
    "deep learning",
    "deno",
    "django",
    "docker",
    "dojo toolkit",
    "elasticsearch",
    "ember.js",
    "etl processes",
    "express.js",
    "fastapi",
    "figma",
    "firebase",
    "flask",
    "flutter",
    "foundation",
    "frontend development",
    "gatsby.js",
    "gcp (google cloud platform)",
    "git",
    "github",
    "gitlab",
    "glimmer.js",
    "go (golang)",
    "google analytics",
    "graphql",
    "grunt",
    "gulp.js",
    "handlebars.js",
    "hibernate",
    "html",
    "ios development",
    "ionic",
    "istio",
    "java",
    "javascript",
    "jenkins",
    "jest",
    "jira",
    "jquery",
    "jsp",
    "json",
    "junit",
    "kafka streams",
    "keras",
    "kubernetes",
    "laravel",
    "less",
    "linux",
    "lodash",
    "machine learning",
    "matlab",
    "mern stack",
    "microservices architecture",
    "microsoft powerapps",
    "mongodb",
    "mongoose",
    "mysql",
    "natural language processing (nlp)",
    "nest.js",
    "next.js",
    "nginx",
    "node.js",
    "nosql databases",
    "numpy",
    "oauth",
    "object-oriented programming (oop)",
    "opencv",
    "oracle database",
    "pandas",
    "perl",
    "php",
    "postgresql",
    "power bi",
    "progressive web apps (pwas)",
    "pyspark",
    "pytorch",
    "python",
    "qt framework",
    "rabbitmq",
    "react",
    "react native",
    "react.js",
    "redux",
    "restful apis",
    "ruby",
    "ruby on rails",
    "rust",
    "saas applications",
    "sass",
    "scala",
    "scrapy",
    "scrum",
    "selenium",
    "shell scripting",
    "socket.io",
    "software development",
    "software testing",
    "spark streaming",
    "spring boot",
    "sql",
    "sqlite",
    "strapi",
    "styled components",
    "swagger",
    "swift",
    "symfony",
    "system design",
    "tableau",
    "tailwind css",
    "tensorflow",
    "terraform",
    "three.js",
    "typescript",
    "ui/ux design",
    "underscore.js",
    "unity 3d",
    "unreal engine",
    "vagrant",
    "vite",
    "virtualization",
    "vue.js",
    "webpack",
    "websockets",
    "wordpress",
    "xamarin",
    "xml",
    "yaml",
    "zabbix",
    "zookeeper"
  ];
  